name: "JFrog-GitHub NPM Publish OIDC Integration"
on: push

permissions:
  id-token: write
jobs:
  build:
     runs-on: ubuntu-latest
     env:
      # OIDC_AUDIENCE: 'jfrog-github'
      OIDC_PROVIDER: 'github'
     defaults:
      run:
        working-directory: ./package
     steps:
       - name: Checkout
         uses: actions/checkout@v3
              
       - name: Setup Node npm
         uses: actions/setup-node@v3
   
       - name: Setup JFrog CLI
         uses: jfrog/setup-jfrog-cli@v4
         env:  
           JF_URL: https://jonw123test.jfrog.io
           
         with:
           oidc-provider-name: ${{ env.OIDC_PROVIDER }}
           version: latest
           # oidc-audience: ${{ env.OIDC_AUDIENCE }}

       - name: get Access token
         run: jf atc > output.json
       
       - name: Install jq
         run: sudo apt-get install -y jq

       - name: Extract access token
         id: extract_token
         run: |
            ACCESS_TOKEN=$(jq -r '.access_token' < output.json)
            echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV
            echo "::set-output name=access_token::$ACCESS_TOKEN"

    # Example step to show how to use the extracted token
       - name: Use access token
         run:  |
           echo "Access Token: ${{ steps.extract_token.outputs.access_token }}"



       
