name: "JFrog-GitHub NPM Publish OIDC Integration"
on: push

permissions:
  id-token: write
jobs:
  build:
     runs-on: ubuntu-latest
     env:
      # OIDC_AUDIENCE: 'jfrog-github'
      OIDC_PROVIDER: 'github'
     defaults:
      run:
        working-directory: ./package
     steps:
       - name: Checkout
         uses: actions/checkout@v3
              
       - name: Setup Node npm
         uses: actions/setup-node@v3
   
       - name: Setup JFrog CLI
         uses: jfrog/setup-jfrog-cli@v4
         env:  
           JF_URL: https://jonw123test.jfrog.io
           
         with:
           oidc-provider-name: ${{ env.OIDC_PROVIDER }}
           version: latest
           # oidc-audience: ${{ env.OIDC_AUDIENCE }}

       - name: get Access token
         run: jf atc 



       
