
name: "JFrog-GitHub wildcard test"
on: push

permissions:
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OIDC_AUDIENCE: 'jfrog-github'
      OIDC_PROVIDER: 'github'
      
    steps:
    - name: Get id token
      run: |
          ID_TOKEN=$(curl -sLS -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=jfrog-github" | jq .value | tr -d '"')
          echo "ID_TOKEN=${ID_TOKEN}" >> $GITHUB_ENV
          
    
    - name: Exchange
      env:
          ARTIFACTORY_URL: https://jonw123test.jfrog.io
      run: |
          ACCESS_TOKEN=$(curl -XPOST https://jonw123test.jfrog.io/access/api/v1/oidc/token -H "Content-type: application/json" -d "{\"grant_type\": \"urn:ietf:params:oauth:grant-type:token-exchange\", \"subject_token_type\":\"urn:ietf:params:oauth:token-type:id_token\", \"subject_token\": \"${{env.ID_TOKEN}}\", \"provider_name\": \"github\"}" | jq .access_token | tr -d '"')
          echo "::add-mask::${ACCESS_TOKEN}"
          echo "ACCESS_TOKEN=${ACCESS_TOKEN}" >> $GITHUB_ENV

    - name: setup-jfrog-cli
      uses: jfrog/setup-jfrog-cli@v4
      env:
       JF_URL: https://jonw123test.jfrog.io/
      with:
       oidc-provider-name: github
    
    # - name: simple curl 
    #   env:
    #       ACCESS_TOKEN: ${{ env.ACCESS_TOKEN }}
    #   run: |
    #       curl -H "Authorization: Bearer $ACCESS_TOKEN" https://jonw123test.jfrog.io/artifactory/api/npm/npm-remote/react

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
          python-version: '3.8'  # Specify the Python version you want to use\

    - name: Install Wheel
      run: |
       python -m pip install --upgrade pip  # Upgrade pip to the latest version
       pip install wheel  # Install the wheel package

    - name: Create Dummy Package
      run: |
          mkdir dummy_package
          echo "from setuptools import setup" > dummy_package/setup.py
          echo "setup(name='dummy-package', version='0.1.0')" >> dummy_package/setup.py
          echo "# Dummy package" > dummy_package/__init__.py
          cd dummy_package
          python setup.py sdist bdist_wheel

    - name: Publish Dummy Package
      run: |
          cd dummy_package
          pip install --upgrade twine  # Ensure Twine is installed
          echo "TWINE_USERNAME=${{ steps.setup-jfrog-cli.outputs.oidc-user }}" >> $GITHUB_ENV
          echo "TWINE_PASSWORD=${{ steps.setup-jfrog-cli.outputs.oidc-token }}" >> $GITHUB_ENV
          
          echo "TWINE_USERNAME=$TWINE_USERNAME"
          echo "TWINE_PASSWORD=$TWINE_PASSWORD"
          twine upload --repository-url https://jonw123test.jfrog.io/artifactory/api/pypi/pypi-local dist/* --username $TWINE_USERNAME --password $TWINE_PASSWORD


       
